version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
  groups:
    maven-dependencies:
      update-types:
        - "patch"
        - "minor"
        - "major"
