CREATE TABLE IF NOT EXISTS `all_type`
(
    `my_id`              varchar(25)                                  NOT NULL,
    `my_int`             int(11)                                      NOT NULL,
    `my_int_null`        int,
    `my_varchar_50`      varchar(50)                                  NOT NULL,
    `my_varchar_50_null` varchar(50),
    `my_varchar_512`     varchar(512)                                 NOT NULL COMMENT 'super varchar 512',
    `my_tinytext`        tinytext                                     NOT NULL,
    `my_mediumtext`      mediumtext                                   NOT NULL,
    `my_longtext`        longtext                                     NOT NULL,
    `my_text`            text                                         NOT NULL,
    `my_char`            char(5)                                      NOT NULL,
    `my_date`            date                                         NOT NULL,
    `my_datetime`        datetime                                     NOT NULL,
    `my_timestamp`       timestamp                                    NOT NULL,
    `my_time`            time                                         NOT NULL,
    `my_year`            year(4)                                      NOT NULL,
    `my_bigint`          bigint(20)                                   NOT NULL,
    `my_tinyint`         tinyint(4)                                   NOT NULL,
    `my_smallint`        smallint(6)                                  NOT NULL COMMENT 'small int comment',
    `my_mediumint`       mediumint(9)                                 NOT NULL,
    `my_decimal`         decimal(19, 5)                               NOT NULL,
    `my_float`           float                                        NOT NULL,
    `my_double`          double                                       NOT NULL,
    `my_enum_sql`        enum ('value_one','value_two','value_three') NOT NULL,
    `my_set`             set ('set_one','set_two','set_three')        NOT NULL,
    `my_bit`             bit(1)                                       NOT NULL,
    `my_bool`            tinyint(1)                                   NOT NULL,
#     `my_binary`          binary(200)                                  NOT NULL, TODO support later if needed
#     `my_varbinary`       varbinary(800)                               NOT NULL, TODO support later if needed
    `my_json`            json                                         NOT NULL,
    `my_geometry`        geometry                                     NOT NULL,
    `my_tinyblob`        tinyblob                                     NOT NULL,
    `my_mediumblob`      mediumblob                                   NOT NULL,
    `my_blob`            blob                                         NOT NULL COMMENT 'blob comment',
    `my_longblob`        longblob                                     NOT NULL,
    `my_tinyint_8`       tinyint(8)                                   NOT NULL,
    PRIMARY KEY (`my_id`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4 COMMENT ='my table comment';
